import { test, expect } from '@playwright/test';

test('dashboard sources lead to visual cases, grounded clarification, and ordinary review', async ({ page, request, context }) => {
  const errors: string[] = [];
  let uploadCalls = 0;
  page.on('request', r => { if (r.url().endsWith('/api/inbox') && r.method() === 'POST') uploadCalls++; });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/overview');
  await expect(page.getByRole('region', { name: 'Data sources', exact: true })).toHaveCount(0);
  await expect(page.getByText('Loading saved claims…')).not.toBeVisible();
  const flow = page.getByRole('region', { name: 'Sources into the audit' });
  await expect(flow).toBeVisible();
  await expect(page.locator('[data-flow-edge="sources-waiting"]')).toHaveCount(1);
  await expect(page.locator('[data-flow-edge]')).toHaveCount(9);
  await page.screenshot({ path: test.info().outputPath('sources-dashboard.png'), fullPage: true });
  await flow.getByRole('link', { name: 'Manage sources' }).click();
  await expect(page.getByRole('heading', { name: 'Your sources. One place to make sense of them.' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Connect', exact: true })).toHaveCount(3);
  await page.getByRole('button', { name: 'Connect', exact: true }).first().click();
  await expect(page.getByRole('dialog')).toContainText('Account connection is not enabled');
  await page.getByRole('button', { name: 'Explore sample data' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByText('event-form-response.csv', { exact: true }).last()).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('source-explorer-before.png'), fullPage: true });
  await page.getByRole('button', { name: 'Read all sample inputs' }).click();
  await expect(page.getByRole('status').first()).toContainText('10 unique documents', { timeout: 30000 });
  await expect(page.getByRole('status').first()).toContainText('1 repeated copy counted once');
  expect(uploadCalls).toBe(10);
  await expect(page.getByLabel('Intake outcomes')).toContainText('1ready to confirm');
  await expect(page.getByLabel('Intake outcomes')).toContainText('1amount to resolve');
  await expect(page.getByRole('region', { name: 'Parsed source fields' })).toContainText('USD 190.00');
  await expect(page.getByRole('region', { name: 'Parsed source fields' })).toContainText('Receipt total');
  const ava = page.getByRole('article', { name: 'Case for Ava Demo: scan-017.pdf', exact: true });
  const maya = page.getByRole('article', { name: 'Case for Maya Demo: IMG_2048.png', exact: true });
  await expect(ava.getByText('Amount differs', { exact: true })).toBeVisible();
  await expect(maya.getByText('Ready to confirm', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Requested amount · USD').first()).not.toBeVisible();
  await page.screenshot({ path: test.info().outputPath('inbox-results-desktop.png'), fullPage: true });

  const ambiguous = page.getByRole('article').filter({ has: page.getByRole('link', { name: 'Re-train-tickets.pdf', exact: true }) }).first();
  await expect(ambiguous.getByLabel('Attach to receipt')).toHaveValue('');
  await ambiguous.getByRole('button', { name: 'Prepare clarification' }).click();
  const composer = page.getByRole('region', { name: 'Clarification draft' });
  await expect(composer.getByLabel('Message')).toHaveValue(/MR-90A/);
  await expect(composer.getByLabel('Message')).toHaveValue(/MR-90B/);
  await expect(composer).toContainText('Draft only · nothing is sent.');
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await composer.getByRole('button', { name: 'Copy draft' }).click();
  await expect(composer.getByRole('button', { name: 'Copied', exact: true })).toBeVisible();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('MR-90A');
  await composer.getByRole('button', { name: 'Close clarification draft' }).click();
  await ambiguous.getByLabel('Attach to receipt').selectOption({ label: 'phone-photo-A.pdf' });
  const ben = page.getByRole('article', { name: 'Case for Ben Demo: phone-photo-A.pdf', exact: true });
  await ben.locator('summary').first().click();
  await ben.getByRole('button', { name: 'Refresh from linked request' }).click();
  await expect(ben.getByLabel('Requested amount · USD')).toHaveValue('120.00');
  await expect(ben.getByText('Ready to confirm', { exact: true })).toBeVisible();
  await ben.locator('summary').first().click();

  await ava.locator('summary').first().click();
  await expect(ava.getByText('$190.00', { exact: true })).toBeVisible();
  await expect(ava.getByText('$180.00', { exact: true })).toBeVisible();
  await expect(ava.getByText('Booking STAY-AVA-901')).toHaveCount(4);
  await ava.getByText('Edit request details', { exact: true }).click();
  await expect(ava.getByLabel('Requested amount · USD')).toHaveValue('190.00');
  await ava.getByRole('checkbox').check();
  await ava.getByLabel('Requested amount · USD').fill('191.00');
  await expect(ava.getByRole('checkbox')).not.toBeChecked();
  await expect(ava.getByRole('button', { name: 'Confirm & send for review' })).toBeDisabled();
  await ava.getByLabel('Requested amount · USD').fill('190.00');
  await ava.getByRole('checkbox').check();
  await page.screenshot({ path: test.info().outputPath('inbox-evidence-desktop.png'), fullPage: true });
  const confirmation = page.waitForResponse(response => response.url().endsWith('/api/inbox/confirm'));
  await ava.getByRole('button', { name: 'Confirm & send for review' }).click();
  const response = await confirmation;
  expect(response.status()).toBe(201);
  const result = await response.json();
  await expect(page.getByText('Claim sent to the review queue')).toBeVisible();
  await expect(ava).toHaveCount(0);
  await expect.poll(async () => {
    const data = await (await request.get('/api/workspace/reviews')).json();
    return data.submissions.find((s: { id: string }) => s.id === result.submission_id)?.assessment_status;
  }, { timeout: 20000 }).toBe('flagged');
  const data = await (await request.get('/api/workspace/reviews')).json();
  const saved = data.submissions.find((s: { id: string }) => s.id === result.submission_id);
  expect(saved.amount_requested_minor).toBe(19000); expect(saved.receipt.parsed_fields_json.amount_minor).toBe(18000);
  expect(saved.decision_status).toBe('pending');
  expect(saved.decisions.find((d: { field_checked: string }) => d.field_checked === 'amount').verdict).toBe('fail');
  const support = await (await request.get(`/api/submissions/${result.submission_id}/supporting-documents`)).json();
  expect(support.documents).toHaveLength(3);
  const receipt = await request.get(`/api/receipts/${result.receipt_id}`);
  expect(receipt.status()).toBe(200); expect((await receipt.body()).subarray(0, 5).toString()).toBe('%PDF-');

  await maya.locator('summary').first().click();
  await expect(maya.getByRole('img')).toBeVisible();
  await expect.poll(() => maya.getByRole('img').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0);
  await maya.getByRole('checkbox').check();
  const mayaSaved = page.waitForResponse(response => response.url().endsWith('/api/inbox/confirm'));
  await maya.getByRole('button', { name: 'Confirm & send for review' }).click();
  expect((await mayaSaved).status()).toBe(201);
  await expect(page.getByRole('link', { name: 'Open saved claim' })).toHaveCount(2);
  await page.getByRole('link', { name: 'Open saved claim' }).first().click();
  await expect(page).toHaveURL(new RegExp(`claim=${result.submission_id}`));
  await page.goto('/overview');
  await expect(page.getByRole('region', { name: 'Sources into the audit' })).toContainText('source files linked to saved cases');
  await page.screenshot({ path: test.info().outputPath('sources-dashboard-after.png'), fullPage: true });
  expect(errors).toEqual([]);
});

test('mobile sources and results fit; unknown formats and unlinked files stay visible', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/overview');
  await expect(page.getByRole('region', { name: 'Sources into the audit' })).toBeVisible();
  await expect(page.locator('[data-flow-edge="sources-waiting"]')).toHaveCount(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath('sources-mobile.png'), fullPage: true });
  await page.goto('/import');
  await page.getByLabel('Upload source files').setInputFiles({ name: 'archive.zip', mimeType: 'application/zip', buffer: Buffer.from('not a zip') });
  await expect(page.getByText('Supported formats: PDF, PNG, JPG, CSV, TXT, and EML. This file could not be read.')).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'Read all sample inputs' }).click();
  await expect(page.getByRole('status').first()).toContainText('10 unique documents', { timeout: 30000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByText('1 file without a supported connection').click();
  await expect(page.getByRole('link', { name: 'weekend-agenda-v3.pdf', exact: true }).last()).toBeVisible();
  const maya = page.getByRole('article', { name: 'Case for Maya Demo: IMG_2048.png', exact: true });
  await maya.locator('summary').first().click();
  await expect(maya.getByRole('img')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath('inbox-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 820, height: 1000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('source reading is visible across tabs and later receipts link to earlier requests', async ({ page, context }) => {
  await page.goto('/import');
  const overview = await context.newPage();
  await overview.goto('/overview');
  let release: (() => void) | undefined;
  await page.route('**/api/inbox', async route => { await new Promise<void>(resolve => { release = resolve; }); await route.continue(); });
  await page.getByRole('button', { name: 'Parse selected row' }).click();
  const flow = overview.getByRole('region', { name: 'Sources into the audit' });
  try { await expect(flow).toContainText('Reading 1 input'); await expect.poll(() => typeof release).toBe('function'); }
  finally { release?.(); }
  await expect(page.getByRole('region', { name: 'Parsed source fields' })).toContainText('USD 190.00');
  await expect(flow).toContainText('1 parsed');
  await expect(page.getByRole('button', { name: 'Read remaining inputs' })).toBeEnabled();
  await page.getByRole('group', { name: 'Sample source' }).getByRole('button', { name: 'File upload' }).click();
  await expect(page.getByRole('region', { name: 'Parsed source fields' })).toContainText('USD 190.00');
  await page.unroute('**/api/inbox');
  await page.getByRole('group', { name: 'Sample source' }).getByRole('button', { name: 'Dropbox' }).click();
  await page.getByRole('button', { name: 'scan-017.pdf PDF', exact: true }).click();
  await page.getByRole('button', { name: 'Parse this input' }).click();
  const ava = page.getByRole('article', { name: 'Case for Ava Demo: scan-017.pdf', exact: true });
  await expect(ava).toContainText('1 supporting file');
  await expect(ava.getByText('Amount differs', { exact: true })).toBeVisible();
  await ava.locator('summary').first().click();
  await expect(ava.getByText('$190.00', { exact: true })).toBeVisible();
  await expect(ava.getByText('$180.00', { exact: true })).toBeVisible();
});
