import { test, expect } from '@playwright/test';
import type { SourceAudit } from '../../src/lib/inbox/schema';

test('Start audit reads messy sources, resumes, and checks only grounded claims', async ({ page, request }) => {
  test.setTimeout(180000);
  const initial = await (await request.get('/api/inbox/audit')).json();
  test.skip(!initial.enabled, 'Run against a fresh demo:inbox server.');
  expect(initial.cursor, 'Use a fresh isolated demo, never reset shared data').toBe(0);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  let release!: () => void;
  const gate = new Promise<void>(resolve => { release = resolve; });
  let first = true;
  await page.route('**/api/inbox/audit', async route => {
    if (route.request().method() !== 'POST' || !first) return route.continue();
    first = false;
    const response = await route.fetch();
    await gate;
    await route.fulfill({ response });
  });
  await page.goto('/overview');
  await expect(page.getByRole('button', { name: 'Start audit', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Start audit', exact: true }).click();
  await expect(page.getByText(/Reading sources ·/)).toBeVisible();
  await page.getByRole('button', { name: 'Stop after active checks' }).click();
  release();
  await expect(page.getByRole('button', { name: 'Continue audit', exact: true })).toBeEnabled({ timeout: 90000 });
  let batch: SourceAudit = await (await request.get('/api/inbox/audit')).json();
  expect(batch.cursor).toBe(1);
  const firstId = batch.documents[0].id;
  await page.reload();
  await page.getByRole('button', { name: 'Start audit', exact: true }).click();
  await expect(page.getByText('Session complete · 2 of 2 claims checked this session')).toBeVisible({ timeout: 120000 });
  batch = await (await request.get('/api/inbox/audit')).json();
  expect(batch.documents[0].id).toBe(firstId);
  expect(batch.documents).toHaveLength(10);
  expect(batch.documents.every(document => !document.error)).toBe(true);
  expect(new Set(batch.documents.map(document => document.file_type))).toEqual(new Set(['application/pdf', 'image/png', 'message/rfc822', 'text/csv']));
  expect(batch.duplicates).toBe(1);
  expect(batch.held).toHaveLength(4);
  expect(batch.imports).toHaveLength(2);
  console.log('Source audit readings', JSON.stringify(batch.documents.map(document => ({ name: document.filename, provenance: document.provenance, latency_ms: document.latency_ms }))));
  const rows = (await (await request.get('/api/workspace/reviews')).json()).submissions;
  expect(rows).toHaveLength(2);
  expect(rows.find((row: { attendee_name: string }) => row.attendee_name === 'Ava Demo')).toMatchObject({ amount_requested_minor: 19000, assessment_status: 'flagged', decision_status: 'pending' });
  expect(rows.find((row: { attendee_name: string }) => row.attendee_name === 'Maya Demo')).toMatchObject({ amount_requested_minor: 4200, assessment_status: 'matched', decision_status: 'approved' });
  await expect(page.getByRole('dialog')).toContainText('4 source inputs still need');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.screenshot({ path: test.info().outputPath('source-audit-overview.png'), fullPage: true });
  const replay = await request.post('/api/inbox/audit', { headers: { origin: new URL(page.url()).origin }, data: {} });
  expect(await replay.json()).toEqual(batch);
  await page.getByRole('link', { name: 'Inspect inputs and connections' }).click();
  await expect(page.getByRole('button', { name: 'All inputs read' })).toBeVisible();
  const ambiguous = page.getByRole('article').filter({ has: page.getByRole('link', { name: 'Re-train-tickets.pdf', exact: true }) }).first();
  await expect(ambiguous.getByLabel('Attach to receipt')).toHaveValue('');
  await expect(page.getByRole('region', { name: 'Parsed source fields' })).toContainText('USD 190.00');
  await page.getByRole('group', { name: 'Sample source' }).getByRole('button', { name: 'Gmail' }).click();
  await page.getByRole('button', { name: 'Fwd-bus-receipt.eml Text export', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Parsed source fields' })).toContainText('USD 42.00');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath('source-audit-inputs-mobile.png'), fullPage: true });
  expect(errors).toEqual([]);
});

test('ordinary workspaces still render with sample-source audit disabled', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/inbox/audit', route => route.fulfill({ json: { enabled: false } }));
  await page.goto('/overview');
  await expect(page.getByRole('heading', { name: 'Follow the audit' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Start audit', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Inspect inputs and connections' })).toHaveCount(0);
  expect(errors).toEqual([]);
});
